.\" danaus.1
.\" Written by Michael Whittaker
.\" 2013-07-31

.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Title
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH danaus 1 2013-07-31 "CS 2110" "User Commands"


.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" NAME
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.SH NAME
.P
danaus - Animalia Arthropoda Insecta Lepidoptera Nymphalidae Danaus

.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" SYNOPSIS
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.SH SYNOPSIS
.P
\fBjava danaus.Simulator\fR [\fB\-\-help\fR] [\fB\-h\fR|\fB\-\-headless\fR] 
[\fB\-d\fR|\fB\-\-debug\fR] [\fB\-w\fR|\fB\-\-warning\fR] [\fB\-i\fR|\fB\-\-infinite\fR]
[\fB\-s\fR|\fB\-\-seed\fR \fIseed\fR] [\fB\-f\fR|\fB\-\-file\fR \fImap_file\fR] 
[\fIbutterfly_class\fR]...

.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" DESCRIPTION
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.SH DESCRIPTION
.P
Danaus is one of the core project sets for Cornell University's CS 2110. Covering concepts from simple object orientation and class hierarchies to graph exploration and machine learning.  


.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" OPTIONS
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.SH OPTIONS
.TP
\fB\-\-help\fR 
.br
display help and exit
.TP
\fB\-h\fR, \fB\-\-headless\fR
execute simulation without a GUI
.TP
\fB\-d\fR, \fB\-\-debug\fR
enable debug printing
.TP
\fB\-w\fR, \fB\-\-warning\fR
enable warning printing
.TP
\fB\-i\fR, \fB\-\-infinite\fR
enable infinite energy
.TP
\fB\-s\fR, \fB\-\-seed\fR \fIseed\fR
use \fIseed\fR to randomly generate map
.TP
\fB\-f\fR, \fB\-\-file\fR \fImap_file\fR
parse \fImap_fle\fR to generate map

.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" MAP FILES
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.SH MAP FILES
.SS Syntax and Grammar
.P
See res/maps/tutorial.xml.

.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" AUTHOR
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.SH AUTHOR
.P
Written by Michael Whittaker with guidance from Professor Ken Birman and Professor David Gries.

.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" REPORTING BUGS
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.SH REPORTING BUGS
.P
Report Danaus bugs to mjw297@cornell.edu, ken@cs.cornell.edu, or gries@cs.cornell.edu.
